### ISSUE TITLE
Pool driver does not handle timed out connections

### ISSUE THREAD

**Issue by ibrt** [johnnadratowski/golang-neo4j-bolt-driver#14]
I'm seeing this issue in production - sometimes pooled connections time out or are otherwise terminated, but they are simply put back in the pool channel, causing permanent failures. Each subsequent reuse of the connection causes an error like this to be generated:

An error occurred running query
An error occured writing length bytes during flush
An error occurred writing to stream
Internal Error(*net.OpError):write tcp 172.18.0.2:36268-\u003e54.242.177.230:24786: write

I suppose the correct behavior would be to discard the connection and open a new one, I can take a stab at fixing this if someone is willing to review the PR.

**Comment by janajri** [comment]
also, seeing this on our end.

**Comment by johnnadratowski** [comment]
@ibrt @janajri - Sorry for the delay on getting back to you on this.  I've been quite busy in my personal life.

I've submitted a PR to fix this issue.  I was able to hook into the points where connection errors could happen, and if they do, I attach the error to the connection so the connection pool knows to discard it and create a new connection.

I wrote a test for this but it's hard to verify if it fixes all cases where this might happen.  Is there any way you could verify this fix?  

Either way, I'm merging it as I think it's a much safer implementation, so you can check it out from the main branch.

**Comment by johnnadratowski** [comment]
@ibrt @janajri - My tests show that this behavior has been fixed, so I'm closing out this issue.  If you find that there are additional issues related to this, please open a new issue and reference this one.

Thanks for the issue report!
