### ISSUE TITLE
unsupported array of strings

### ISSUE THREAD

**Issue by janajri** [johnnadratowski/golang-neo4j-bolt-driver#15]
I noticed that the driver is incapable of encoding an array of strings
```
processor.go:87: An error occurred running query
	An error occurred encoding a struct field
		Unrecognized type when encoding data for Bolt transport: []string [53a388f017bf0d3d1faeef22]
```

**Comment by janajri** [comment]
just noticed there's a PR to address this issue, closing.

**Comment by vin047** [comment]
**For others encountering this issue**

The pull request @janajri is referring to is here: https://github.com/johnnadratowski/golang-neo4j-bolt-driver/pull/8

Until its merged (if at all...), a workaround is to join your string array into a single string using an appropriate deliminator, and encode the parameter (as a string) using this driver. Then in your cypher query, split the string back to an array (https://neo4j.com/docs/developer-manual/current/cypher/functions/string/#functions-split). Bit long winded but can confirm that it works
