### ISSUE TITLE
Close all connections in the Pool

### ISSUE THREAD

**Issue by chrisaxiom** [johnnadratowski/golang-neo4j-bolt-driver#27]
Hello, thanks for the great library.  Do you know if there is a way to close all of the open connections in the pool?  I am thinking it would be needed upon shutdown of the app.

**Comment by chrisaxiom** [comment]
ping @johnnadratowski

**Comment by Matt-Guest** [comment]
@johnnadratowski My team has also encountered this problem. We forked your repo and have made a patch to allow all the connections in a pool to be closed. In the next day or so, we will be making a pull request on your repo to address this issue.

**Comment by johnnadratowski** [comment]
This should be resolved with the latest PR
