### ISSUE TITLE
Can't run basic `conn, err := driver.OpenNeo("bolt://localhost:7687")`

### ISSUE THREAD

**Issue by mttchrry** [johnnadratowski/golang-neo4j-bolt-driver#28]
when I run the following lines of code with `bolt "github.com/johnnadratowski/golang-neo4j-bolt-driver"` imported :
> driver := bolt.NewDriver()
> 	//neo4jUrl := "bolt://localhost:7687"
> 	conn, err := driver.OpenNeo("bolt://localhost:7687")
> 	if err != nil {
> 		return nil, err
> 	}

I get the error:
An error occurred decoding ack failure message response
                Couldn't read expected bytes for message length. Read: 0 Expected: 2.

I'm on windows, and double checked my config that it should be 7687 for bolt connections. Any help?

**Comment by mttchrry** [comment]
yeah, didn't include username/password.. oops

**Comment by AlexanderDaw** [comment]
Why is the username / password connection pattern not documented anywhere?
