### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by qoshi** [johnnadratowski/golang-neo4j-bolt-driver#3]
1. Will this project support more neo4j api like neoism or you just want to do this with SQL?
2. How to contribute to this repo?

**Comment by johnnadratowski** [comment]
@qoshi 

1. The API exposed by these interfaces is compatible with the SQL driver interface, but also defines extra interfaces on top of that overall structure.  I've added several methods on top of the base structure that provide more convenience when using the library.  I'm open to discussing the addition of extra interfaces.  However, there is a line that I would draw on how complex they should be.  I think if one wanted to build an ORM-like interface, that should occur in a separate project, but that could leverage this library.
2. I would love to have extra contributors to this repo.   If you follow the dev quickstart in the README it should give you a good starting point for developing against this repository.  There is some funkiness with how Travis CI works with the tests, as the tests are an integration testing style.  Let me know if what is documented is unclear.

Happy to see you're interested in the project.

**Comment by johnnadratowski** [comment]
@qoshi - please let me know if I've answered your concerns satisfactorily and I'll close this issue.

**Comment by qoshi** [comment]
I mean should I fork one and make a pull request after follow the README?

**Comment by johnnadratowski** [comment]
@qoshi - Yes, you can fork and make a PR

**Comment by johnnadratowski** [comment]
@qoshi - since I haven't heard from you, I assume this answers your question, and am closing the issue.
