### ISSUE TITLE
ImpermanentGraphDatabase?

### ISSUE THREAD

**Issue by martin-flower** [johnnadratowski/golang-neo4j-bolt-driver#31]
The neo4j documentation refers to the ImpermanentGraphDatabase (for unittesting). Is this something that will become available from Go one day?

**Comment by robbert229** [comment]
The `ImpermanentGraphDatabase` is only useable on a language that runs on the JVM. 
[source](https://stackoverflow.com/a/41538902/1781412)

**Comment by johnnadratowski** [comment]
Thanks @robbert229 for the reference. Seems to be out of scope.  Closing this issue.
