### ISSUE TITLE
Cannot read from rows.NextNeo() - graph.Node not exported

### ISSUE THREAD

**Issue by anne-markis** [johnnadratowski/golang-neo4j-bolt-driver#52]
I'm probably doing something obviously wrong here, so I'd appreciate any push in the right direction.

I see in the examples something like 

```
data, _, err = rows.NextNeo()
fmt.Printf("FIELDS: %d %f\n", data[0].(int64), data[1].(float64))
```

However, when I do this, I get a `Panic: interface conversion` error. And when I check the type -

```
fmt.Printf("Type: ", reflext.typeOf(data[0]))
```

I get `graph.Node`.

Since it is not exported, I'm unable to do a type assertion `d[0].(graph.Node)` as I get this compile issue: "cannot refer to unexported name golangNeo4jBoltDriver.graph".

Is there a better way to read from `rows.NextNext()` that I'm missing?

**Comment by umsu2** [comment]
copy and paste your import statement for the graph

**Comment by anne-markis** [comment]
```
import (
	"fmt"
	"io"
	"reflect"

	bolt "github.com/johnnadratowski/golang-neo4j-bolt-driver"
)
```

Note that `d[0].(bolt.graph.Node)` is also not exported.

**Comment by umsu2** [comment]
import neo4jgraph "github..../golang-neo4j-bolt-driver/structures/graph"

then type assert to neo4jgraph.Node
this is not an issue for the library.

**Comment by anne-markis** [comment]
Doh. That did it. Thanks!
