### ISSUE TITLE
Graphene connection error when reading server version ( go1.12 )

### ISSUE THREAD

**Issue by mpiivonen** [johnnadratowski/golang-neo4j-bolt-driver#64]
We have been running same version of neo4j hosted by ourself and haven't had any problems. Now we are going to use 3rd party provider for hosting and encountered following problem:

go version go1.12.2 linux/amd64

err An error occurred initializing connection
	An error occurred reading server version
Internal Error(*errors.errorString):EOF

 Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack(0x8b12f7, 0x28, 0x0)
	/snap/go/3584/src/runtime/debug/stack.go:24 +0x9d
github.com/johnnadratowski/golang-neo4j-bolt-driver/errors.Wrap(0x9a9e40, 0xc000078030, 0x8b12f7, 0x28, 0x0, 0x0, 0x0, 0xc0001c6000)
	/xx/xx/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/errors/errors.go:38 +0x186
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).handShake(0xc0001c6000, 0x9b5360, 0xc0000900c8)
	/xx/xx/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:253 +0x2aa
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).initialize(0xc0001c6000, 0xc0001c6000, 0x4)
	/xx/xx/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:292 +0x83
github.com/johnnadratowski/golang-neo4j-bolt-driver.newBoltConn(0xc000068180, 0x5e, 0xc000090090, 0xc000111f78, 0xc00017a000, 0x0)
	/xx/xx/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:102 +0xd5
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltDriver).OpenNeo(0xc000090090, 0xc000068180, 0x5e, 0x8, 0xc000068180, 0x5e, 0x0)
	/xx/xx/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/driver.go:64 +0x3f

I did notice couple year old issue with tls and tried to add but doesn't seem to make any difference.
Tested connection from the machine by using python script with same credentials and it works nicely.

Thanks.

**Comment by collisonchris** [comment]
I haven't tried go 1.12 at all with the driver, very recent releases there(~a month ago); does using 1.11 or 1.10 work?

**Comment by mpiivonen** [comment]
Tested with 11.1 and got same error.
Tested with 10.1 and with that seems to work.

I'll double check with 11.1 when adding ?tls=true and get back to you

**Comment by vin047** [comment]
I ran into this issue myself this week, running Neo4j 3.3.2 Community Edition on FreeBSD. Compiling with go 1.11.5 seems to have fixed it for me too

**Comment by mpiivonen** [comment]
I think this is more relevant how neo4j server has been configured rather than driver itself.
https://neo4j.com/docs/operations-manual/current/configuration/connectors/
