### ISSUE TITLE
please add a readme

### ISSUE THREAD

**Issue by jexp** [johnnadratowski/golang-neo4j-bolt-driver#9]
To give users a quick intro in how to get started and also provide links to Neo4j and the driver.

Perhaps also provide info on how to deploy, e.g. to heroku?

**Comment by johnnadratowski** [comment]
@jexp - I've decided that, in order to facilitate deploying to heroku, I'd move the example out to a separate repo:  https://github.com/johnnadratowski/golang-bolt-movie-example

Let me know what you think.

**Comment by jexp** [comment]
Yes, that makes sense and is also what I had in mind initially. Thanks!

Von meinem iPhone gesendet

**Comment by johnnadratowski** [comment]
@jexp - Thanks, closing this issue.
